apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-worker
  namespace: argocd
spec:
  destination:
    namespace: mercel
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/maxmurr/mercel
    targetRevision: main
    path: infra/workloads/deploy-worker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
